### PR TITLE
christy-branch: include application foundation

### PR DESCRIPTION
**Pull request by christyyoo**
Included a bunch of folders/files to help us start building our web application :)

### CODE REVIEW

**Comment by jeffreychai** [comment]
This looks great! These files seem awesome to help us jumpstart everything.

**Comment by kimdo20** [comment]
Tested locally and got it up and running; looks good!

**Review by emkulka — APPROVED** [review]
Looks good to me!

**Review by abagramian — CHANGES_REQUESTED** [review]
Verified to work locally, good starter code to implement other features. Before merging, please remove all unessecary items (react pngs and favicon, reportwebvitals for now)

**Review by kimdo20 — COMMENTED** [review]
Tested locally and got it up and running; looks good!

**Review by jeffreychai — COMMENTED** [review]
Adding all of these files will provide a good foundation.

**Review by abagramian — APPROVED** [review]
cleaned out unused files, still works locally, looks good

**Pull request merged**
